tup1=(10,)
print(tup1)
tup2= 1,4,5
print(tup2)
tpl = tuple(range(4,10,2))
list4 = list(range(4,10,2))
print(tpl,list4)
print('min=' ,min(tpl))
print('max=',max(tpl))
print('count=',tpl.count(4))
print('length=',len(tpl))
tpnew=(1,8,7,2,0,-7)
print(sorted(tpnew))
print('index of',tpnew.index(2))